language: ruby
rvm:
  - 2.1.5
cache: bundler
notifications:
  email: false
before_install:
  - gem update --system 2.2.2
  - gem install bundler --version 1.7.4
  - gem --version
  - bundle --version
