couch_host: 'localhost'
couch_port: 5984
couch_database: 'users'
#couch_user: 'nickserver'
#couch_password: 'blahblah'
hkp_url: 'https://hkps.pool.sks-keyservers.net:/pks/lookup'
port: 6425
pid_file: '/var/run/nickserver'
user: 'nobody'
log_file: '/var/log/nickserver.log'
